2019-06-17T21:13:00|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:00|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:00|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:00|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:00|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:00|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:01|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:01|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:01|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:01|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:01|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:01|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:01|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:01|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:01|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:01|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:02|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:02|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:02|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:02|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:02|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:02|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:02|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:02|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:02|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:03|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:03|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:03|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:03|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:03|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:03|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:03|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:03|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:03|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:04|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:04|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:04|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:04|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:04|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:04|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:04|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:04|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:04|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:05|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:05|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:05|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:05|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:05|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:05|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:05|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:05|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:05|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:06|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:06|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:06|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:06|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:06|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:06|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:06|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:07|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:07|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:07|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:07|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:07|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:07|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:08|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:08|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:08|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:08|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:08|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:09|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:09|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:09|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:09|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:10|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:10|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:10|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:10|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:10|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:11|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:11|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:11|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:11|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:12|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:12|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:12|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:12|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:12|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:13|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
2019-06-17T21:13:13|ERROR|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer Failed to update figure1: Plot data must be 1D ndarray.. ['Traceback (most recent call last):\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundry\\measurement.py", line 279, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\lab\\Documents\\foundry_scope\\ScopeFoundryHW\\picoquant\\hydraharp_optimizer.py", line 148, in update_display\n    self.plotlines[rate].setData(y = self.optimize_history[:i])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 461, in setData\n    self.updateItems()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotDataItem.py", line 487, in updateItems\n    self.curve.setData(x=x, y=y, **curveArgs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 307, in setData\n    self.updateData(*args, **kargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyqtgraph\\graphicsItems\\PlotCurveItem.py", line 329, in updateData\n    raise Exception("Plot data must be 1D ndarray.")\n', 'Exception: Plot data must be 1D ndarray.\n']
