2019-06-17T19:45:19|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundry\measurement.py", line 183, in _thread_run
    self.run()
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundryHW\picoquant\hydraharp_optimizer.py", line 116, in run
    self.optimize_history_std[self.optimize_ii,:] = np.std(self.optimize_history, (0,1) )
AttributeError: 'HydraHarpOptimizerMeasure' object has no attribute 'optimize_history_std'

2019-06-17T19:45:22|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundry\measurement.py", line 183, in _thread_run
    self.run()
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundryHW\picoquant\hydraharp_optimizer.py", line 116, in run
    self.optimize_history_std[self.optimize_ii,:] = np.std(self.optimize_history, (0,1) )
AttributeError: 'HydraHarpOptimizerMeasure' object has no attribute 'optimize_history_std'

